"use client"

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
// import { Providers } from './providers';
import './globals.css';
import { PetraWallet } from "petra-plugin-wallet-adapter";
import { ThemeProvider } from "@/components/ThemeProvider";
import { WalletProvider } from "@/components/WalletProvider";
import { AutoConnectProvider } from "@/components/AutoConnectProvider";
import { Toaster } from '@/components/ui/toaster';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'

const wallets = [new PetraWallet()];
const queryClient = new QueryClient()


const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'GitFund: Eth Denver 2024',
//   description: 'Generated by create next app',
// };

// Updated RootLayout to handle session being undefined
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
      <QueryClientProvider client={queryClient}>
        {/* <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        > */}
          <AutoConnectProvider>
            <WalletProvider>
              {/* <Providers> */}
                <div className='bg-white overflow-x-hidden'>{children}</div>
                <Toaster />
              {/* </Providers> */}
            </WalletProvider>
          </AutoConnectProvider>
          <ReactQueryDevtools initialIsOpen={false} />
        {/* </ThemeProvider> */}
        </QueryClientProvider>
      </body>
    </html>
  );
  
}
